
language: node_js
sudo: true

os:
  - linux

node_js:
  - "10.15.0"


install:
  - yarn install
  - sudo apt-get install unzip
  - yarn audit fix

script:
  - yarn run lint
  - yarn run build
  - yarn run pack:web-ext
  - yarn run pack:chrome-crx