
language: node_js
sudo: false

os:
  - linux

node_js:
  - "10.15.0"


install:
  - yarn install
  - apt-get install unzip

script:
  - yarn run lint
  - yarn run build
  - yarn run pack:web-ext
  - yarn run pack:chrome-crx